#!/bin/sh
set -e
name=rpmlint-tests
#last_commit=(`git rev-list --timestamp HEAD^..HEAD`)
#date=`date +%Y%m%d%H%M -d "1970-01-01 00:00 UTC $last_commit seconds"`
fn=$name.tar.bz2
git archive --prefix=$name/ HEAD | bzip2 > $fn
echo "$fn"
